version: 0.2

phases:
  install:
    commands:
      - echo "No install needed."
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - python ./deploy_rule_templates.py $OUTPUT_BUCKET
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
