#
# Copyright 2017-2018 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License").
# You may not use this file except in compliance with the License.
# A copy of the License is located at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# or in the "license" file accompanying this file. This file is distributed 
# on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either 
# express or implied. See the License for the specific language governing 
# permissions and limitations under the License.
#

AWSTemplateFormatVersion: 2010-09-09
Description: Sets up the RuleSet
Parameters:
  SourceLambdaBucket:
    Type: String
    Description: Bucket name where lambda code zips are placed
    MaxLength: 63
    MinLength: 3
    ConstraintDescription: Enter the name not the ARN, must be in the same region than the stack
  LambdaRuleIAMRoleARN:
    Type: String
    Description: IAM Role used by Lambda

Resources:

#
# BEGINNING OF THE RESOURCES SECTION TO BE ADAPTED TO YOUR NEEDS
# Modify your rule set here (sample below). Each new Custom Config rule of the ruleSet needs 1) Lambda Function and 2) Lambda Permission. The CFn Stack includes the necessary.
# For managed rules, the configuration is to be done in application-account-setup.yaml
#

  CreateCLOUDTRAILCERuleStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join ['/', ['https://s3.amazonaws.com', !Ref SourceLambdaBucket, 'compliance-account-rule-lambda-setup.yaml']]
      Parameters:
        RuleSetName: CLOUDTRAIL_CENTRALIZED_ENCRYPTED_LFI
        SourceLambdaBucket: !Ref SourceLambdaBucket
        LambdaRuleRoleARN: !Ref LambdaRuleIAMRoleARN

  CreateCLOUDWATCHEVRuleStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join ['/', ['https://s3.amazonaws.com', !Ref SourceLambdaBucket, 'compliance-account-rule-lambda-setup.yaml']]
      Parameters:
        RuleSetName: CLOUDWATCH_EVENT_BUS_CENTRALIZED
        SourceLambdaBucket: !Ref SourceLambdaBucket
        LambdaRuleRoleARN: !Ref LambdaRuleIAMRoleARN

  CreateCONFIGENABLERuleStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join ['/', ['https://s3.amazonaws.com', !Ref SourceLambdaBucket, 'compliance-account-rule-lambda-setup.yaml']]
      Parameters:
        RuleSetName: CONFIG_ENABLED_CENTRALIZED
        SourceLambdaBucket: !Ref SourceLambdaBucket
        LambdaRuleRoleARN: !Ref LambdaRuleIAMRoleARN

  CreateGUARDDUTYENARuleStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join ['/', ['https://s3.amazonaws.com', !Ref SourceLambdaBucket, 'compliance-account-rule-lambda-setup.yaml']]
      Parameters:
        RuleSetName: GUARDDUTY_ENABLED_CENTRALIZED
        SourceLambdaBucket: !Ref SourceLambdaBucket
        LambdaRuleRoleARN: !Ref LambdaRuleIAMRoleARN

  CreateIAMPOLICYNOFRuleStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join ['/', ['https://s3.amazonaws.com', !Ref SourceLambdaBucket, 'compliance-account-rule-lambda-setup.yaml']]
      Parameters:
        RuleSetName: IAM_POLICY_NO_FULL_STAR
        SourceLambdaBucket: !Ref SourceLambdaBucket
        LambdaRuleRoleARN: !Ref LambdaRuleIAMRoleARN

  CreateKMSCMKROTATIRuleStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join ['/', ['https://s3.amazonaws.com', !Ref SourceLambdaBucket, 'compliance-account-rule-lambda-setup.yaml']]
      Parameters:
        RuleSetName: KMS_CMK_ROTATION_ENABLED
        SourceLambdaBucket: !Ref SourceLambdaBucket
        LambdaRuleRoleARN: !Ref LambdaRuleIAMRoleARN

  CreateROOTMFAENABLRuleStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join ['/', ['https://s3.amazonaws.com', !Ref SourceLambdaBucket, 'compliance-account-rule-lambda-setup.yaml']]
      Parameters:
        RuleSetName: ROOT_MFA_ENABLED
        SourceLambdaBucket: !Ref SourceLambdaBucket
        LambdaRuleRoleARN: !Ref LambdaRuleIAMRoleARN

  CreateROOTNOACCESSRuleStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join ['/', ['https://s3.amazonaws.com', !Ref SourceLambdaBucket, 'compliance-account-rule-lambda-setup.yaml']]
      Parameters:
        RuleSetName: ROOT_NO_ACCESS_KEY
        SourceLambdaBucket: !Ref SourceLambdaBucket
        LambdaRuleRoleARN: !Ref LambdaRuleIAMRoleARN

  CreateROOTNOLASTACRuleStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join ['/', ['https://s3.amazonaws.com', !Ref SourceLambdaBucket, 'compliance-account-rule-lambda-setup.yaml']]
      Parameters:
        RuleSetName: ROOT_NO_LAST_ACCESS
        SourceLambdaBucket: !Ref SourceLambdaBucket
        LambdaRuleRoleARN: !Ref LambdaRuleIAMRoleARN

  CreateVPCMAINROUTERuleStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join ['/', ['https://s3.amazonaws.com', !Ref SourceLambdaBucket, 'compliance-account-rule-lambda-setup.yaml']]
      Parameters:
        RuleSetName: VPC_MAIN_ROUTE_TABLE_NO_IGW
        SourceLambdaBucket: !Ref SourceLambdaBucket
        LambdaRuleRoleARN: !Ref LambdaRuleIAMRoleARN

  CreateVPCSECURITYGRuleStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join ['/', ['https://s3.amazonaws.com', !Ref SourceLambdaBucket, 'compliance-account-rule-lambda-setup.yaml']]
      Parameters:
        RuleSetName: VPC_SECURITY_GROUP_DEFAULT_BLOCKED
        SourceLambdaBucket: !Ref SourceLambdaBucket
        LambdaRuleRoleARN: !Ref LambdaRuleIAMRoleARN


#
# END OF THE RESOURCES SECTION TO BE ADAPTED
#

  CreateCOMPLIANCERURuleStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join ['/', ['https://s3.amazonaws.com', !Ref SourceLambdaBucket, 'compliance-account-rule-lambda-setup.yaml']]
      Parameters:
        RuleSetName: COMPLIANCE_RULESET_LATEST_INSTALLED
        SourceLambdaBucket: !Ref SourceLambdaBucket
        LambdaRuleRoleARN: !Ref LambdaRuleIAMRoleARN